### ISSUE TITLE
Latest Commit breaks the game

### ISSUE THREAD

**Issue by NightDevel** [ajanata/PretendYoureXyzzy#131]
The latest commit causes "internal server error" to be thrown in global chat.  Card sets don't appear to load once "New game" is pressed.  Reverting back two commits before 359c5e11404644688da85b14336074a43a45ca07 fixes the issue.  Note: I haven't tested one commit before 359c5e11404644688da85b14336074a43a45ca07 out of pure laziness.  Sorry.

**Comment by ajanata** [comment]
The server I am running is on 358c5e1 and appears to be working fine. Some people are reporting issues but not that specific problem (more like the javascript or css isn't loading properly than anything).

I think there's some caching problems going on, which is odd since there's supposed to be a filter that says to not cache anything, unless I broke that somehow when I was making it work in Jetty...
