### ISSUE TITLE
Complete Instructions? Missing base deck.

### ISSUE THREAD

**Issue by crisvuchs** [ajanata/PretendYoureXyzzy#158]
I have been recently trying to install the server on my laptop running ubuntu 16.04 with java 8 and tomcat 7, but cannot play a game because the base card deck is not available. I am not sure I have the correct files installed, but I have got it running on the tomcat server and am able to access it, but there are no cardsets available to choose a base deck from.

**Comment by rkemper** [comment]
I had this same issue when I initially installed.  It was because the java application could not communicate with the database.  This is because I sent a different password for the database than what the application was expecting.  Make sure that the hibernate.cfg.xml has the correct credentials stored that matches your database setup.  See this link for more info: https://gist.github.com/BenTech2/4ff95d173a5ff6a5f657

**Comment by ajanata** [comment]
Don't edit the hibernate.cfg.xml file directly. Edit build.properties and change the values there. They automatically get injected into hibernate.cfg.xml when you run mvn.

**Comment by ajanata** [comment]
That said, the build.properties.example, if used directly, should Just Work with the provided SQLite file.
