### ISSUE TITLE
Server crashes when first player joins

### ISSUE THREAD

**Issue by twiceineverymoment** [ajanata/PretendYoureXyzzy#264]
Setting up a PYX server for my group, using the command `mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false` the application builds and starts successfully, but crashes as soon as the first player clicks "Set" on the nickname screen.

This seems to happen _some of the time_ when that player is connecting over the internet, but _every time_ if that player is connecting to the server via its LAN address from another device on the same network or via localhost.

I've installed it on both a Raspberry Pi 3 B+ and a desktop running Ubuntu 20.04, and both experience the same problem.

Attaching a log file that appears in the Maven directory following a crash.
[hs_err_pid18521.log](https://github.com/ajanata/PretendYoureXyzzy/files/7884254/hs_err_pid18521.log)

**Comment by Noorquacker** [comment]
Obvious question, but are you on Java 7 and Tomcat 7 both?

**Comment by twiceineverymoment** [comment]
There is no Tomcat install, the server is being run according to the quick start guide using this command from a terminal:
`mvn clean package war:exploded jetty:run -Dmaven.buildNumber.doCheck=false -Dmaven.buildNumber.doUpdate=false `
The Ubuntu server is using OpenJDK 11.

**Comment by Noorquacker** [comment]
Yeah, Java versions above 7 just straight up crash, it happened to me back when I tried using Tomcat 8. This project is unmaintained so it's doubtful that you'll get any more support for this. When I set this up so many years ago, I had to go out of my way to install Tomcat 7, which was a real pain.
If you want dark theme for everyone and MySQL support instead of PostgreSQL, I did [make a fork](https://github.com/Noorquacker/PretendYoureXyzzy) a long time ago

**Comment by twiceineverymoment** [comment]
Doesn't compile with Java 7 (code contains lambda expressions which are Java 8 minimum), but I downloaded OpenJDK 8 and ran with Jetty on another server and it seems to work ok. The first server had Java 11 which seemed to cause the crash.
