### ISSUE TITLE
Getting this running...

### ISSUE THREAD

**Issue by bacon420** [ajanata/PretendYoureXyzzy#38]
I don't really know about jsp, but when loading (index.jsp) I get XML parsing error right at the begging at <%--.    Tried on ubuntu 10, 12, and win7.    Sadly my group is all C#/.NET users and this just blows our minds.  

http://i.imgur.com/7Pab9cT.png

**Comment by oasis9** [comment]
I wonder if anyone's still around.. I've recently taken up the task of getting this running, and I'm hitting plenty road blocks. Not sure what the current issue is due to, that being: `SEVERE: Error configuring application listener of class net.socialgamer.cah.StartupUtils
java.lang.ClassNotFoundException: net.socialgamer.cah.StartupUtils`
I fixed an earlier issue relating to javax.servlet-api.jar which was being exported as part of the .war file, and was conflicting with Tomcat 7's libraries. Now, however, there's this issue, and I'm not sure what to do about it.

**Comment by dopeghoti** [comment]
Are you trying to host this directly in Tomcat?  I just fire the servlet up in a `screen` session using `mvn clean package war:exploded jetty:run`, and use Apache to kick a more friendly URL over to the Java process.

**Comment by oasis9** [comment]
I am :stuck_out_tongue: I'm on Windows, I should probably get a Ubuntu machine running, but haven't gotten around to it. When I run that maven command from within the project directory, it fails due to the same error I've had in eclipse. It's not due to build.properties.example not having been copied build.properties, fyi. The hibernate library doesn't seem to be properly imported, or is the wrong version, because it causes a few errors, which looking in eclipse, have to do with Hibernate.class not having the type variables available, as they were transitioned to StandardDataTypes.class, and also errors regarding org.hibernate.Query being indirectly accessed by imports, but not being part of the build path. Is there something wrong in my development environment, say JDK/JRE version, Tomcat, etc? I've been working with Java for a decent time now, but I've next to no experience with web application development.
